version: '3.7'

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    command: bash script.sh
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: testproj-db-1
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"