# Generated by Django 4.2.3 on 2023-07-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.CharField(max_length=100, verbose_name='Расшифровка')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Наименование')),
                ('core', models.IntegerField(verbose_name='Общее колличество ядер')),
                ('frequency', models.FloatField(verbose_name='Базовая частота процессора ГГц')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('diagonal', models.FloatField(verbose_name='Диагональ экрана')),
                ('matrix', models.CharField(max_length=100, verbose_name='Технология изготовления матрицы')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type', models.CharField(max_length=100, verbose_name='Тип памяти')),
                ('frequency', models.IntegerField(verbose_name='Тактовая частота МГц')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('model', models.CharField(max_length=100, verbose_name='Модели ЦАП')),
                ('capacity', models.IntegerField(verbose_name='Разрядность АЦП')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
    ]
