# Generated by Django 4.2.3 on 2023-07-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Tanım'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core',
            field=models.IntegerField(verbose_name='Toplam çekirdek sayısı'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='frequency',
            field=models.FloatField(verbose_name='CPU taban frekansı GHz'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.TextField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='diagonal',
            field=models.FloatField(verbose_name='Ekran köşegeni'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='matrix',
            field=models.CharField(max_length=100, verbose_name='Matris üretim teknolojisi'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.IntegerField(verbose_name='Saat frekansı MHz'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Bellek türü'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='capacity',
            field=models.IntegerField(verbose_name='ADC bit derinliği'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='model',
            field=models.CharField(max_length=100, verbose_name='DAC Modelleri'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
    ]
