# Generated by Django 4.2.3 on 2023-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_categories_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core',
            field=models.IntegerField(verbose_name='Общее колличество ядер'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='frequency',
            field=models.FloatField(verbose_name='Базовая частота процессора ГГц'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='diagonal',
            field=models.FloatField(verbose_name='Диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='matrix',
            field=models.CharField(max_length=100, verbose_name='Технология изготовления матрицы'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.IntegerField(verbose_name='Тактовая частота МГц'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='capacity',
            field=models.IntegerField(verbose_name='Разрядность АЦП'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модели ЦАП'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='soundcard',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
